#pragma once
#include "Global.h"

std::string en_US = R"(
death.attack.anvil=%1$s was squashed by a falling anvil
death.attack.anvil.player=%1$s was squashed by a falling anvil during a fight with %2$s
death.attack.anvil.item=%1$s was squashed by a falling anvil while fighting %2$s holding %3$s
death.attack.arrow=%1$s was shot by %2$s
death.attack.arrow.player=%1$s was shot by %2$s
death.attack.arrow.item=%1$s was shot by %2$s using %3$s
death.attack.bullet=%1$s was sniped by %2$s
death.attack.bullet.player=%1$s was sniped by %2$s
death.attack.cactus=%1$s was pricked to death
death.attack.cactus.player=%1$s collided with a cactus while trying to escape %2$s
death.attack.cactus.item=%1$s collided with a cactus while trying to escape %2$s holding %3$s
death.attack.drown=%1$s drowned
death.attack.drown.player=%1$s drowned while trying to escape %2$s
death.attack.drown.item=%1$s drowned while trying to escape %2$s holding %3$s
death.attack.explosion=%1$s exploded
death.attack.explosion.player=%1$s was blown up by %2$s
death.attack.explosion.item=%1$s was blown up by %2$s using %3$s
death.attack.badRespawnPoint.message=%1$s was killed by [intentional game design]
death.attack.fall=%1$s hit the ground too hard
death.attack.fall.player=%1$s hit the ground too hard while trying to escape %2$s
death.attack.fall.item=%1$s hit the ground too hard while trying to escape %2$s holding %3$s
death.attack.fallingBlock=%1$s was squashed by a falling block
death.attack.fallingBlock.player=%1$s was squashed by a falling block during a fight with %2$s
death.attack.fallingBlock.item=%1$s was squashed by a falling block while fighting %2$s holding %3$s
death.attack.fireball=%1$s was incinerated by %2$s fireball
death.attack.fireball.player=%1$s was incinerated by %2$s fireball
death.attack.fireball.item=%1$s was incinerated by %2$s fireball launched using %3$s
death.attack.fireworks=%1$s vanished with a bang
death.attack.fireworks.player=%1$s vanished with a bang while fighting %2$s
death.attack.fireworks.item=%1$s vanished with a bang caused by %2$s launching %3$s
death.attack.flyIntoWall=%1$s experienced kinetic energy
death.attack.flyIntoWall.player=%1$s experienced kinetic energy while trying to escape %$s
death.attack.flyIntoWall.item=%1 felt the force of kinetic energy while trying to escape from %2$s holding %3$s
death.attack.generic=%1$s died
death.attack.generic.player=%1$s died from %2$s
death.attack.indirectMagic=%1$s was killed by magic used by %2$s
death.attack.indirectMagic.player=%1$s was killed by magic used by %2$s
death.attack.indirectMagic.item=%1$s was killed by %2$s using %3$s
death.attack.inFire=%1$s was consumed by fire
death.attack.inFire.player=%1$s accidentally walked into fire while fighting %2$s
death.attack.inFire.item=%1$s accidentally walked into fire while fighting %2$s holding %3$s
death.attack.inWall=%1$s suffocated in a wall
death.attack.inWall.player=%1$s suffocated in a wall while fighting %2$s
death.attack.inWall.item=%1$s suffocated in a wall while fighting %2$s holding %3$s
death.attack.lava=%1$s tried to swim in lava
death.attack.lava.player=%1$s tried to swim in lava while trying to escape from %2$s
death.attack.lava.item=%1$s tried to swim in lava while trying to escape from %2$s holding %3$s
death.attack.lightningBolt=%1$s was struck by lightning
death.attack.lightningBolt.player=%1$s was struck by lightning while fighting %2$s
death.attack.lightningBolt.item=%1$s was struck by lightning while fighting %2$s holding %3$s
death.attack.magic=%1$s was killed by magic
death.attack.hotFloor=%1$s discovered the floor was made of lava
death.attack.hotFloor.player=%1$s stepped into danger due to %2$s
death.attack.hotFloor.item=%1$s stepped into danger due to %2$s holding %3$s
death.attack.mob=%1$s was killed by %2$s
death.attack.mob.item=%1$s was killed by %2$s using %3$s
death.attack.sting=%1$s was stung to death by %2$s
death.attack.sting.player=%1$s was stung to death by %2$s
death.attack.sting.item=%1$s was stung to death by %2$s using %3$s
death.attack.onFire=%1$s was burned to death
death.attack.onFire.player=%1$s was crispy fried while fighting %2$s
death.attack.onFire.item=%1$s was crispy fried while fighting %2$s holding %3$s
death.attack.outOfWorld=%1$s fell out of the world
death.attack.outOfWorld.player=%1$s and %2$s don't share the same world
death.attack.outOfWorld.item=%1$s was slain by %2$s
death.attack.player=%1$s was killed by %2$s
death.attack.player.item=%1$s was killed by %2$s using %3$s
death.attack.spit=%1$s drowned in %2$s's spit
death.attack.starve=%1$s starved to death
death.attack.starve.player=%1$s starved to death while fighting %2$s
death.attack.starve.item=%1$s starved to death while fighting %2$s holding %3$s
death.attack.sweetBerry=%1$s was pricked to death by sweet berry bushes
death.attack.sweetBerry.player=%1$s was pricked to death by sweet berry bushes while trying to escape %2$s
death.attack.sweetBerry.item=%1$s was pricked to death by sweet berry bushes while trying to escape %2$s holding %3$s
death.attack.thorns=%1$s was killed trying to hurt %2$s
death.attack.thorns.player=%1$s was killed trying to hurt %2$s
death.attack.thorns.item=%1$s was killed by %3$s when trying to hurt %2$s
death.attack.thrown=%1$s was pummeled by %2$s
death.attack.thrown.player=%1$s was pummeled by %2$s
death.attack.thrown.item=%1$s was pummeled by %2$s using %3$s
death.attack.trident=%1$s was impaled by %2$s
death.attack.trident.player=%1$s was impaled by %2$s
death.attack.trident.item=%1$s was impaled by %2$s using %3$s
death.attack.wither=%1$s withered away
death.attack.wither.player=%1$s withered away while fighting %2$s
death.attack.wither.item=%1$s withered away while fighting %2$s holding %3$s
death.attack.freeze=%1$s froze to death
death.attack.freeze.player=%1$s was frozen to death by %2$s
death.attack.freeze.item=%1$s was frozen to death by %2$s holding %3$s
death.attack.sonicBoom=%1$s was obliterated by a sonic boom
death.attack.sonicBoom.item=%1$s was obliterated by a sonic boom while trying to escape %2$s
death.attack.sonicBoom.player=%1$s was obliterated by a sonic boom while trying to escape %2$s
death.attack.stalactite=%1$s was impaled by a falling stalactite
death.attack.stalactite.player=%1$s was impaled by a falling stalactite while battling %2$s
death.attack.stalactite.item=%1$s was impaled by a falling stalactite while battling %2$s holding %3$s
death.attack.stalagmite=%1$s was impaled by a stalagmite
death.attack.stalagmite.player=%1$s was impaled by a stalagmite while battling %2$s
death.attack.stalagmite.item=%1$s was impaled by a stalagmite while battling %2$s holding %3$s
death.attack.witherSkull=%1$s was shot and killed by a wither skull launched by %2$s
death.attack.witherSkull.player=%1$s was shot and killed by a wither skull launched by %2$s
death.attack.witherSkull.item=%1$s was shot and killed by a wither skull launched by %2$s using %3$s
death.attack.even_more_magic=%1$s was killed by unknown magic
death.attack.genericKill=%1$s was slain
death.attack.genericKill.player=%1$s was slain by %2$s
death.attack.genericKill.item=%1$s was slain by %2$s holding %3$s
death.attack.dragonBreath=%1$s was cooked by dragon's breath
death.attack.dragonBreath.player=%1$s was cooked by %2$s's dragon breath
death.attack.dryout=%1$s died of dehydration
death.attack.dryout.player=%1$s died of dehydration while trying to escape from %2$s
death.attack.outsideBorder=%1$s left this world
death.attack.outsideBorder.player=%1$s left this world while battling %2$s
death.fell.accident.generic=%1$s fell from a high place
death.fell.assist=%1$s was doomed to fall by %2$s
death.fell.assist.item=%1$s was doomed to fall by %2$s using %3$s
death.fell.finish=%1$s fell too far and was finished by %2$s
death.fell.finish.player=%1$s fell too far and was finished by %2$s
death.fell.finish.item=%1$s fell too far and was finished by %2$s using %3$s
death.fell.killer=%1$s was doomed to fall
multiplayer.player.joined=%s joined the game
multiplayer.player.left=%s left the game
plugin.deathmessages.modapi.warn=The optional Dependency plugin ModAPI is not loaded, so client-side translation is unavailable. Only server-side translation can be used.
)";

std::string zh_CN = R"(
death.attack.anvil=%1$s 被坠落的铁砧压扁了
death.attack.anvil.player=%1$s 在与 %2$s 战斗时被坠落的铁砧压扁了
death.attack.anvil.item=%1$s 在与持有 %3$s 的 %2$s 战斗时被坠落的铁砧压扁了
death.attack.arrow=%1$s被 %2$s 射杀
death.attack.arrow.player=%1$s被 %2$s 射杀
death.attack.arrow.item=%1$s 被 %2$s 用 %3$s 射杀
death.attack.bullet=%1$s被 %2$s 狙击了
death.attack.bullet.player=%1$s被 %2$s 狙击了
death.attack.cactus=%1$s 被戳死了
death.attack.cactus.player=%1$s 在试图逃离 %2$s 时撞上了仙人掌
death.attack.cactus.item=%1$s 在试图逃离持有 %3$s 的 %2$s 时撞上了仙人掌
death.attack.drown=%1$s 淹死了
death.attack.drown.player=%1$s 在试图逃离 %2$s 时淹死了
death.attack.drown.item=%1$s 在试图逃离持有 %3$s 的 %2$s 时淹死了
death.attack.explosion=%1$s 爆炸了
death.attack.explosion.player=%1$s 被 %2$s 炸死了
death.attack.explosion.item=%1$s 被 %2$s 使用 %3$s 炸死了
death.attack.badRespawnPoint.message=%1$s 被 [刻意的游戏设计] 杀死了
death.attack.fall=%1$s 落地过猛
death.attack.fall.player=%1$s 在试图逃离 %2$s 时落地过猛
death.attack.fall.item=%1$s 在试图逃离持有 %3$s 的 %2$s 时落地过猛
death.attack.fallingBlock=%1$s 被坠落的方块压扁了
death.attack.fallingBlock.player=%1$s 在与 %2$s 战斗时被坠落的方块压扁了
death.attack.fallingBlock.item=%1$s 在与持有 %3$s 的 %2$s 战斗时被坠落的方块压扁了
death.attack.fireball=%1$s被 %2$s 用火球烧死了
death.attack.fireball.player=%1$s被 %2$s 用火球烧死了
death.attack.fireball.item=%1$s被 %2$s 用 %3$s 发射的火球烧死了
death.attack.fireworks=%1$s 随着一声巨响消失了
death.attack.fireworks.player=%1$s 在与 %2$s 战斗时随着一声巨响消失了
death.attack.fireworks.item=%1$s 随着 %2$s 用 %3$s 发射的烟花发出的巨响消失了
death.attack.flyIntoWall=%1$s 感受到了动能
death.attack.flyIntoWall.player=%1$s 在试图逃离 %2$s 时感受到了动能
death.attack.flyIntoWall.item=%1$s 在试图逃离持有 %3$s 的 %2$s 时感受到了动能
death.attack.generic=%1$s 死了
death.attack.generic.player=%1$s 死于 %2$s
death.attack.indirectMagic=%1$s 被 %2$s 使用的魔法杀死了
death.attack.indirectMagic.player=%1$s 被 %2$s 使用的魔法杀死了
death.attack.indirectMagic.item=%1$s 被 %2$s 用 %3$s 杀死了
death.attack.inFire=%1$s 浴火焚身
death.attack.inFire.player=%1$s 在与 %2$s 战斗时不慎走入了火中
death.attack.inFire.item=%1$s 在与持有 %3$s 的 %2$s 战斗时不慎走入了火中
death.attack.inWall=%1$s 在墙里窒息而亡
death.attack.inWall.player=%1$s 在与 %2$s 战斗时在墙里窒息而亡
death.attack.inWall.item=%1$s 在与持有 %3$s 的 %2$s 战斗时在墙里窒息而亡
death.attack.lava=%1$s 试图在熔岩里游泳
death.attack.lava.player=%1$s 在试图逃离 %2$s 时试图在熔岩里游泳
death.attack.lava.item=%1$s 在试图逃离持有 %3$s 的 %2$s 时试图在熔岩里游泳
death.attack.lightningBolt=%1$s 被闪电击中
death.attack.lightningBolt.player=%1$s 在与 %2$s 战斗时被闪电击中
death.attack.lightningBolt.item=%1$s 在与持有 %3$s 的 %2$s 战斗时被闪电击中
death.attack.magic=%1$s 被魔法杀死了
death.attack.hotFloor=%1$s 发现地板是熔岩做的
death.attack.hotFloor.player=%1$s 因 %2$s 而步入危险之地
death.attack.hotFloor.item=%1$s 因持有 %3$s 的 %2$s 而步入危险之地
death.attack.mob=%1$s 被 %2$s 杀死了
death.attack.mob.player=%1$s 被 %2$s 杀死了
death.attack.mob.item=%1$s 被 %2$s 用 %3$s 杀死了
death.attack.sting=%1$s 被 %2$s 蛰死了
death.attack.sting.player=%1$s 被 %2$s 蛰死了
death.attack.sting.item=%1$s 被 %2$s 用 %3$s 蛰死了
death.attack.onFire=%1$s 被烧死了
death.attack.onFire.player=%1$s 在与 %2$s 战斗时被烤的酥脆
death.attack.onFire.item=%1$s 在与持有 %3$s 的 %2$s 战斗时被烤的酥脆
death.attack.outOfWorld=%1$s 掉出了这个世界
death.attack.outOfWorld.player=%1$s 与 %2$s 不共戴天
death.attack.outOfWorld.item=%1$s 与持有 %3$s 的 %2$s 不共戴天
death.attack.player=%1$s 被 %2$s 杀死了
death.attack.player.item=%1$s 被 %2$s 用 %3$s 杀死了
death.attack.spit=%1$s 被 %2$s 的口水淹死了
death.attack.starve=%1$s 饿死了
death.attack.starve.player=%1$s 在与 %2$s 战斗时饿死了
death.attack.starve.item=%1$s 在与持有 %3$s 的 %2$s 战斗时饿死了
death.attack.sweetBerry=%1$s 被甜浆果丛刺死了
death.attack.sweetBerry.player=%1$s 在试图逃离 %2$s 时被甜浆果丛刺死了
death.attack.sweetBerry.item=%1$s 在试图逃离持有 %3$s 的 %2$s 时被甜浆果丛刺死了
death.attack.thorns=%1$s 在试图伤害 %2$s
death.attack.thorns.player=%1$s 在试图伤害 %2$s 时被杀
death.attack.thorns.item=%1$s 在试图伤害 %2$s 时被 %3$s 杀死
death.attack.thrown=%1$s 被 %2$s 给砸死了
death.attack.thrown.player=%1$s 被 %2$s 给砸死了
death.attack.thrown.item=%1$s 被 %2$s 用 %3$s 给砸死了
death.attack.trident=%1$s 被 %2$s 刺穿了
death.attack.trident.player=%1$s 被 %2$s 刺穿了
death.attack.trident.item=%1$s 被 %2$s 使用 %3$s 刺穿了
death.attack.wither=%1$s 凋零了
death.attack.wither.player=%1$s 在与 %2$s 战斗时凋零了
death.attack.wither.item=%1$s 在与持有 %3$s 的 %2$s 战斗时凋零了
death.attack.freeze=%1$s 被冻死了
death.attack.freeze.player=%1$s 被 %2$s 冻死了
death.attack.freeze.item=%1$s 被持有 %3$s 的 %2$s 冻死了
death.attack.sonicBoom=%1$s 被一道音波尖啸抹除了
death.attack.sonicBoom.player=%1$s 在试图逃离 %2$s 时被一道音波尖啸抹除了
death.attack.sonicBoom.item=%1$s 在试图逃离 %2$s 时被一道音波尖啸抹除了
death.attack.stalactite=%1$s 被坠落的钟乳石刺穿了
death.attack.stalactite.player=%1$s 在与 %2$s 战斗时被坠落的钟乳石刺穿了
death.attack.stalactite.item=%1$s 在与持有 %3$s 的 %2$s 战斗时被坠落的钟乳石刺穿了
death.attack.stalagmite=%1$s 被石笋刺穿了
death.attack.stalagmite.player=%1$s 在与 %2$s 战斗时被石笋刺穿了
death.attack.stalagmite.item=%1$s 在与持有 %3$s 的 %2$s 战斗时被石笋刺穿了
death.attack.witherSkull=%1$s 被 %2$s 发射的头颅射杀
death.attack.witherSkull.player=%1$s 被 %2$s 发射的头颅射杀
death.attack.witherSkull.item=%1$s 被 %2$s 用 %3$s 发射的头颅射杀
death.attack.even_more_magic=%1$s 被不为人知的魔法杀死了
death.attack.genericKill=%1$s 被杀死了
death.attack.genericKill.player=%1$s 在与 %2$s 战斗时被杀死了
death.attack.genericKill.item=%1$s 在与持有 %3$s 的 %2$s 战斗时被杀死了
death.attack.dragonBreath=%1$s 被龙息烤熟了
death.attack.dragonBreath.player=%1$s 被 %2$s 的龙息烤熟了
death.attack.dryout=%1$s 因脱水而死
death.attack.dryout.player=%1$s 在试图逃离 %2$s 时因脱水而死
death.attack.outsideBorder=%1$s 脱离了这个世界
death.attack.outsideBorder.player=%1$s 在与 %2$s 战斗时脱离了这个世界
death.fell.accident.generic=%1$s 从高处摔了下来
death.fell.assist=%1$s 因为 %2$s 注定要摔死
death.fell.assist.item=%1$s 因为 %2$s 使用了 %3$s 注定要摔死
death.fell.finish=%1$s 摔伤得太重并被 %2$s 完结了生命
death.fell.finish.player=%1$s 摔伤得太重并被 %2$s 完结了生命
death.fell.finish.item=%1$s 摔伤得太重并被 %2$s 用 %3$s 完结了生命
death.fell.killer=%1$s 注定要摔死


multiplayer.player.joined=%s 加入了游戏
multiplayer.player.left=%s 退出了游戏
plugin.deathmessages.modapi.warn=可选依赖ModAPI没有被加载，所以客户端侧翻译无法使用，正在启用服务端侧翻译
)";